### ISSUE TITLE
Gearshift Up and Down option

### ISSUE THREAD

**Issue by sh4z4n** [R1PeR/MouseToVJoy#1]
Hi, i love your program, actually is much better than any mouse scripts from GlovePie or FreePIE but is very boring because i can't configure the Gearshift. Would be so cool if you could add this options on "config.txt":

GearshiftUpKey 
GearshiftDownKey

**Comment by R1PeR** [comment]
I would love to but I havent found good way to emulate vjoy button press within vjoyinterface libary

**Comment by R1PeR** [comment]
Done, have fun with it :)
