### ISSUE TITLE
Steering ignores mouse acceleration(enhanced pointer precision)

### ISSUE THREAD

**Issue by N0-Time** [R1PeR/MouseToVJoy#12]
I recently tried using your program for asseto corsa and it worked perfectly, but the problem is it ignores mouse acceleration/enhanced pointer precision. This makes it impossible for me to drive properly since when I originally learnt mouse steering on LFS ~3 years ago I did so with mouse acceleration active.

I'm not sure if there is anything you can do about this (a way to toggle raw input on/off, or if you can't do that with vjoy maybe you could add your own mouse acceleration setting?), but if you can I'd greatly appreciate it.

**Comment by R1PeR** [comment]
Yes it ignores it, because of raw input, one thing that I can recommend is using Intercept Mouse Accel Filter, which I am using too

**Comment by N0-Time** [comment]
Thanks for the advice, I spent a few hours trying to get something that felt right but didn't succeed, guess I'll try some more another time. Great program though.
