### ISSUE TITLE
Error missing dll files only in version 1.5

### ISSUE THREAD

**Issue by sh4z4n** [R1PeR/MouseToVJoy#2]
When i open the MouseToVJoy from 1.5 i got 3 errors of missing dll:

"A code execution can not continue because MSVCP140D.dll was not found. Reinstalling the program to correct the problem."
![768le9avsustgdolemltvg](https://user-images.githubusercontent.com/33049259/33229999-a9c6903c-d1c1-11e7-8c23-f54539e2542f.png)

"A code execution can not continue because VCRUNTIME140D.dll was not found. Reinstalling the program to correct the problem."
![nli6rjfith6tzjerjmtzua](https://user-images.githubusercontent.com/33049259/33230023-35515b32-d1c2-11e7-9866-b5cf1b1aa83e.png)

"A code execution can not continue because ucrtbased.dll was not found. Reinstalling the program to correct the problem."
![igsorze2tsuyg3kckwguqa](https://user-images.githubusercontent.com/33049259/33230020-14b201a6-d1c2-11e7-948a-ecaa94471498.png)

So after put them on SysWOW64 for try to fix this i got a other error:
![slabeckzscqj5l10tykvuq](https://user-images.githubusercontent.com/33049259/33230093-040c4882-d1c4-11e7-9bd6-bcb8e905a738.png)
"The application could not be initialized correctly (0xc000007b)."

As you can see in the screenshot below, version 1.4 works correctly:
![uxvhflpkrmoppc2t_tuvmg](https://user-images.githubusercontent.com/33049259/33230148-5a0073ac-d1c5-11e7-9547-8df65694bfb4.png)

**Comment by R1PeR** [comment]
I haven't used nothing new in 1.5, but I compiled it on Windows 10, try to reinstall Microsoft Visual C++ Redistributable 2015, If this is not the case, then I will recompile it and maybe this will fix this issue. (I am currently using 1.5 version without any problem.)

**Comment by sh4z4n** [comment]
That's weird, i already tried to reinstall Microsoft Visual C++ Redistributable 2015 even without knowing about it but didn't work.

**Comment by sh4z4n** [comment]
That's weird, i already tried to reinstall Microsoft Visual C++ Redistributable 2015 x64 and x86 because of another aplication but didn't work.

**Comment by sh4z4n** [comment]
That's weird, i already tried to reinstall Microsoft Visual C++ Redistributable 2015 x64 and x86 but didn't work.

**Comment by R1PeR** [comment]
I think it can be a problem on my side. I will recompile it and you will check then

**Comment by sh4z4n** [comment]
Oh ok

**Comment by R1PeR** [comment]
Check it now. I reinstalled my VS and recompiled MTVJ, if it won't fix it, then I don't know what will.

**Comment by sh4z4n** [comment]
Damn, nothing.

**Comment by R1PeR** [comment]
hmm I really have no idea what is the problem. I will try to find a fix,

**Comment by ghost** [comment]
I have the same problem, 1.41 works without any problems.

**Comment by R1PeR** [comment]
Try installing x86 vc redist 2015 maybe this will fix the issue

**Comment by R1PeR** [comment]
"Some systems will not allow the install unless older C++ 2015 Redistributable files are removed first. It is recommended that you uninstall all the versions of the packet (Visual C++ 2005, Visual C++ 2008, Visual C++ 2010, Visual C++ 2015) and then reinstall them."

**Comment by R1PeR** [comment]
Recompiled it using new settings and both 32 and 64 bit versions.
[Release.zip](https://github.com/R1PeR/MouseToVJoy/files/1598745/Release.zip)

**Comment by sh4z4n** [comment]
Good work, finally fixed!
