### ISSUE TITLE
Missing dll files error in version 1.6 Beta 2

### ISSUE THREAD

**Issue by GoodMemoriez** [R1PeR/MouseToVJoy#4]
Exactly the same problem as other guy had in 1.5 release, tried all the same steps and cant run the program.
I wonder if anyone figured the fix for that.

**Comment by R1PeR** [comment]
Trying to find a fix right now.

**Comment by R1PeR** [comment]
Try installing x86 vc redist 2015 maybe this will fix the issue

**Comment by R1PeR** [comment]
"Some systems will not allow the install unless older C++ 2015 Redistributable files are removed first. It is recommended that you uninstall all the versions of the packet (Visual C++ 2005, Visual C++ 2008, Visual C++ 2010, Visual C++ 2015) and then reinstall them."

**Comment by R1PeR** [comment]
Recompiled it using new settings and both 32 and 64 bit versions.
[Release.zip](https://github.com/R1PeR/MouseToVJoy/files/1598745/Release.zip)

**Comment by GoodMemoriez** [comment]
That helped! Thank you!
