### ISSUE TITLE
Wheel veering to the left when UseForceFeedback is set to 1

### ISSUE THREAD

**Issue by ghost** [R1PeR/MouseToVJoy#5]
I'm not sure how you implemented it but the wheel is constantly going left, even when stationary.

**Comment by R1PeR** [comment]
For now it only works with constant force feedback(live for speed uses one). Later I will try to implement other types of forcefeedback

**Comment by R1PeR** [comment]
BTW. what version are you using?

**Comment by ghost** [comment]
1.61, sorry forgot to mention it.

**Comment by R1PeR** [comment]
x64 or x86? if you are using x64 then try x86, because it have problems with running. Anyway I will look into it and see if I can find anything.
