### ISSUE TITLE
Mouse axis and Handbreake detection

### ISSUE THREAD

**Issue by sh4z4n** [R1PeR/MouseToVJoy#6]
I'm using the recompiled version x64. Almost buttons works only Handbreake does not detect, same with Mouse axis in Assetto Corsa, rFactor but LFS works fine.

**Comment by R1PeR** [comment]
use x86 version, there is a problem with compiled x64 one

**Comment by sh4z4n** [comment]
Thank you for quick reply but i no need to use recompiled version anymore because for some strange reason 1.6.2 worked perfectly here.

**Comment by xCuri0** [comment]
@R1PeR where can i download x86 ?
